# Lines configured by zsh-newuser-install

################################################################################
# PATH
#
################################################################################
#
#
#
#
#
# TODO
#
#
#
#
PATH=/usr/local/texlive/2017/bin/x86_64-linux:$PATH
#
#
#
#
## Appends every command to the history file once it is executed
setopt inc_append_history
# Reloads the history whenever you use it
setopt share_history

HISTFILE=$HOME/.histfile
HISTSIZE=1000
SAVEHIST=1000

# vim mode
bindkey -v

# Use vim cli mode
bindkey '^P' up-history
bindkey '^N' down-history

# backspace and ^h working even after
# returning from command mode
bindkey '^?' backward-delete-char
bindkey '^h' backward-delete-char

# ctrl-w removed word backwards
bindkey '^w' backward-kill-word

# ctrl-r starts searching history backward
bindkey '^r' history-incremental-search-backward

bindkey '^a' beginning-of-line
# bindkey '^a' vi-beginning-of-line
bindkey '^e' end-of-line
# bindkey '^e' vi-end-of-line

# powerline
. /usr/lib/python2.7/site-packages/powerline/bindings/zsh/powerline.zsh

# adjust delay when switching modes to .1 seconds
export KEYTIMEOUT=1

# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
# zstyle :compinstall filename '$HOME/.zshrc'

autoload -Uz compinit
compinit
zstyle ':completion:*' auto-description 'specify: %d'
zstyle ':completion:*' completer _expand _complete _correct _approximate
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' menu select=2 eval "$(dircolors -b)"
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=* l:|=*'
zstyle ':completion:*' menu select=long
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' use-compctl false
zstyle ':completion:*' verbose true
zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd'

# End of lines added by compinstall
source $HOME/.alias

# Sleep added to avoid warning issued by xmodmap because some keys are pressed
sleep 0.1
xmodmap $HOME/.Xmodmap

# Syntax highlighting in shell
# This should always be the last one being sourced
source /home/kitesutra/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
