# Lines configured by zsh-newuser-install

################################################################################
# PATH
#
################################################################################
#
#
#
#
#
# TODO
#
#
#
#
PATH=/usr/local/texlive/2017/bin/x86_64-linux:$PATH
#
#
#
#
## Appends every command to the history file once it is executed
setopt inc_append_history
# Reloads the history whenever you use it
setopt share_history

HISTFILE=$HOME/.histfile
HISTSIZE=1000
SAVEHIST=1000

# vim mode
bindkey -v

# Use vim cli mode
bindkey '^P' up-history
bindkey '^N' down-history

# backspace and ^h working even after
# returning from command mode
bindkey '^?' backward-delete-char
bindkey '^h' backward-delete-char

# ctrl-w removed word backwards
bindkey '^w' backward-kill-word

# ctrl-r starts searching history backward
bindkey '^r' history-incremental-search-backward

bindkey '^a' beginning-of-line
# bindkey '^a' vi-beginning-of-line
bindkey '^e' end-of-line
# bindkey '^e' vi-end-of-line

# powerline
. /usr/lib/python2.7/site-packages/powerline/bindings/zsh/powerline.zsh

# adjust delay when switching modes to .1 seconds
export KEYTIMEOUT=1

# ZMV allows to mass-rename
autoload zmv
alias zmv='noglob zmv'
alias zcp='noglob zmv -C'
alias zln='noglob zmv -L'
alias zsy='noglob zmv -Ls'


# zstyle :compinstall filename '$HOME/.zshrc'
autoload -Uz compinit
compinit
# zstyle ':completion:*' auto-description 'specify: %d'
# # zstyle ':completion:*' completer _expand _complete _correct _approximate
# zstyle ':completion:*' completer _expand _complete 
# zstyle ':completion:*' format 'Completing %d'
# zstyle ':completion:*' group-name ''
# zstyle ':completion:*' menu select=2 eval "$(dircolors -b)"
# zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
# zstyle ':completion:*' list-colors ''
# zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
# zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=* l:|=*'
# zstyle ':completion:*' menu select=long
# zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
# zstyle ':completion:*' use-compctl false
# zstyle ':completion:*' verbose true
# zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
# zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd'
# Do menu-driven completion.
zstyle ':completion:*' menu select

# Color completion for some things.
# http://linuxshellaccount.blogspot.com/2008/12/color-completion-using-zsh-modules-on.html
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}

# formatting and messages
# http://www.masterzen.fr/2009/04/19/in-love-with-zsh-part-one/
zstyle ':completion:*' verbose yes
zstyle ':completion:*:descriptions' format "$fg[yellow]%B--- %d%b"
zstyle ':completion:*:messages' format '%d'
zstyle ':completion:*:warnings' format "$fg[red]No matches for:$reset_color %d"
zstyle ':completion:*:corrections' format '%B%d (errors: %e)%b'
zstyle ':completion:*' group-name ''

# Completers for my own scripts
zstyle ':completion:*:*:sstrans*:*' file-patterns '*.(lst|clst)'
zstyle ':completion:*:*:ssnorm*:*' file-patterns '*.tsv'

# NO FUNCIONA
# unsetopt correct_all
# DISABLE_CORRECTION="true"
# setopt CSH_NULL_GLOB
# unsetopt correct_all

# End of lines added by compinstall
source $HOME/.alias

# Sleep added to avoid warning issued by xmodmap because some keys are pressed
sleep 0.1
xmodmap $HOME/.Xmodmap

# Syntax highlighting in shell
# This should always be the last one being sourced
source /home/kitesutra/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
